namespace: purestorage
name: flasharray
version: 1.1.1
readme: README.md
authors:
- Pure Storage Ansible Team (@sdodsley) <pure-ansible-team@purestorage.com>
description: Collection of modules to manage Pure Storage FlashArrays (including Cloud Block Store)
license:
 - GPL-2.0-or-later
tags:
  - purestorage
  - flasharray
  - cloudblockstore
  - storage
dependencies: {}
repository: https://github.com/Pure-Storage-Ansible/FlashArray-Collection
documentation: https://github.com/Pure-Storage-Ansible/FlashArray-Collection
issues: https://github.com/Pure-Storage-Ansible/FlashArray-Collection/issues
