namespace: PureStorage
name: flasharray
version: 0.9.0
readme: README.md
authors:
- Pure Storage Ansible Team (@sdodsley) <pure-ansible-team@purestorage.com>
description: Collection of modules to manage Pure Storage FlashArrays
license:
 - GPL-2.0-or-later
tags:
  - purestorage
  - flasharray
  - storage
dependencies: {}
repository: https://github.com/Pure-Storage-Ansible/FlashArray-Collection
documentation: https://github.com/Pure-Storage-Ansible/FlashArray-Collection
issues: https://github.com/Pure-Storage-Ansible/FlashArray-Collection/issues
