objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    purefa_ad:
      description: Manage FlashArray Active Directory Account
      name: purefa_ad
      namespace: ''
      version_added: 1.9.0
    purefa_admin:
      description: Configure Pure Storage FlashArray Global Admin settings
      name: purefa_admin
      namespace: ''
      version_added: 1.12.0
    purefa_alert:
      description: Configure Pure Storage FlashArray alert email settings
      name: purefa_alert
      namespace: ''
      version_added: 1.0.0
    purefa_apiclient:
      description: Manage FlashArray API Clients
      name: purefa_apiclient
      namespace: ''
      version_added: 1.5.0
    purefa_arrayname:
      description: Configure Pure Storage FlashArray array name
      name: purefa_arrayname
      namespace: ''
      version_added: 1.0.0
    purefa_banner:
      description: Configure Pure Storage FlashArray GUI and SSH MOTD message
      name: purefa_banner
      namespace: ''
      version_added: 1.0.0
    purefa_certs:
      description: Manage FlashArray SSL Certificates
      name: purefa_certs
      namespace: ''
      version_added: 1.8.0
    purefa_connect:
      description: Manage replication connections between two FlashArrays
      name: purefa_connect
      namespace: ''
      version_added: 1.0.0
    purefa_console:
      description: Enable or Disable Pure Storage FlashArray Console Lock
      name: purefa_console
      namespace: ''
      version_added: 1.0.0
    purefa_default_protection:
      description: Manage SafeMode default protection for a Pure Storage FlashArray
      name: purefa_default_protection
      namespace: ''
      version_added: 1.14.0
    purefa_directory:
      description: Manage FlashArray File System Directories
      name: purefa_directory
      namespace: ''
      version_added: 1.5.0
    purefa_dirsnap:
      description: Manage FlashArray File System Directory Snapshots
      name: purefa_dirsnap
      namespace: ''
      version_added: 1.9.0
    purefa_dns:
      description: Configure FlashArray DNS settings
      name: purefa_dns
      namespace: ''
      version_added: 1.0.0
    purefa_ds:
      description: Configure FlashArray Directory Service
      name: purefa_ds
      namespace: ''
      version_added: 1.0.0
    purefa_dsrole:
      description: Configure FlashArray Directory Service Roles
      name: purefa_dsrole
      namespace: ''
      version_added: 1.0.0
    purefa_endpoint:
      description: Manage VMware protocol-endpoints on Pure Storage FlashArrays
      name: purefa_endpoint
      namespace: ''
      version_added: 1.0.0
    purefa_eradication:
      description: Configure Pure Storage FlashArray Eradication Timer
      name: purefa_eradication
      namespace: ''
      version_added: 1.9.0
    purefa_eula:
      description: Sign Pure Storage FlashArray EULA
      name: purefa_eula
      namespace: ''
      version_added: 1.0.0
    purefa_export:
      description: Manage FlashArray File System Exports
      name: purefa_export
      namespace: ''
      version_added: 1.5.0
    purefa_fs:
      description: Manage FlashArray File Systems
      name: purefa_fs
      namespace: ''
      version_added: 1.5.0
    purefa_hg:
      description: Manage hostgroups on Pure Storage FlashArrays
      name: purefa_hg
      namespace: ''
      version_added: 1.0.0
    purefa_host:
      description: Manage hosts on Pure Storage FlashArrays
      name: purefa_host
      namespace: ''
      version_added: 1.0.0
    purefa_info:
      description: Collect information from Pure Storage FlashArray
      name: purefa_info
      namespace: ''
      version_added: 1.0.0
    purefa_inventory:
      description: Collect information from Pure Storage FlashArray
      name: purefa_inventory
      namespace: ''
      version_added: 1.0.0
    purefa_kmip:
      description: Manage FlashArray KMIP server objects
      name: purefa_kmip
      namespace: ''
      version_added: 1.10.0
    purefa_maintenance:
      description: Configure Pure Storage FlashArray Maintence Windows
      name: purefa_maintenance
      namespace: ''
      version_added: 1.7.0
    purefa_messages:
      description: List FlashArray Alert Messages
      name: purefa_messages
      namespace: ''
      version_added: 1.14.0
    purefa_network:
      description: Manage network interfaces in a Pure Storage FlashArray
      name: purefa_network
      namespace: ''
      version_added: 1.0.0
    purefa_ntp:
      description: Configure Pure Storage FlashArray NTP settings
      name: purefa_ntp
      namespace: ''
      version_added: 1.0.0
    purefa_offload:
      description: Create, modify and delete NFS, S3 or Azure offload targets
      name: purefa_offload
      namespace: ''
      version_added: 1.0.0
    purefa_pg:
      description: Manage protection groups on Pure Storage FlashArrays
      name: purefa_pg
      namespace: ''
      version_added: 1.0.0
    purefa_pgsched:
      description: Manage protection groups replication schedules on Pure Storage
        FlashArrays
      name: purefa_pgsched
      namespace: ''
      version_added: 1.0.0
    purefa_pgsnap:
      description: Manage protection group snapshots on Pure Storage FlashArrays
      name: purefa_pgsnap
      namespace: ''
      version_added: 1.0.0
    purefa_phonehome:
      description: Enable or Disable Pure Storage FlashArray Phonehome
      name: purefa_phonehome
      namespace: ''
      version_added: 1.0.0
    purefa_pod:
      description: Manage AC pods in Pure Storage FlashArrays
      name: purefa_pod
      namespace: ''
      version_added: 1.0.0
    purefa_pod_replica:
      description: Manage ActiveDR pod replica links between Pure Storage FlashArrays
      name: purefa_pod_replica
      namespace: ''
      version_added: 1.0.0
    purefa_policy:
      description: Manage FlashArray File System Policies
      name: purefa_policy
      namespace: ''
      version_added: 1.5.0
    purefa_proxy:
      description: Configure FlashArray phonehome HTTPs proxy settings
      name: purefa_proxy
      namespace: ''
      version_added: 1.0.0
    purefa_ra:
      description: Enable or Disable Pure Storage FlashArray Remote Assist
      name: purefa_ra
      namespace: ''
      version_added: 1.0.0
    purefa_saml:
      description: Manage FlashArray SAML2 service and identity providers
      name: purefa_saml
      namespace: ''
      version_added: 1.12.0
    purefa_smis:
      description: Enable or disable FlashArray SMI-S features
      name: purefa_smis
      namespace: ''
      version_added: 1.0.0
    purefa_smtp:
      description: Configure FlashArray SMTP settings
      name: purefa_smtp
      namespace: ''
      version_added: 1.0.0
    purefa_snap:
      description: Manage volume snapshots on Pure Storage FlashArrays
      name: purefa_snap
      namespace: ''
      version_added: 1.0.0
    purefa_snmp:
      description: Configure FlashArray SNMP Managers
      name: purefa_snmp
      namespace: ''
      version_added: 1.0.0
    purefa_sso:
      description: Configure Pure Storage FlashArray Single Sign-On
      name: purefa_sso
      namespace: ''
      version_added: 1.9.0
    purefa_subnet:
      description: Manage network subnets in a Pure Storage FlashArray
      name: purefa_subnet
      namespace: ''
      version_added: 1.0.0
    purefa_syslog:
      description: Configure Pure Storage FlashArray syslog settings
      name: purefa_syslog
      namespace: ''
      version_added: 1.0.0
    purefa_syslog_settings:
      description: Manage FlashArray syslog servers settings
      name: purefa_syslog_settings
      namespace: ''
      version_added: 1.10.0
    purefa_timeout:
      description: Configure Pure Storage FlashArray GUI idle timeout
      name: purefa_timeout
      namespace: ''
      version_added: 1.0.0
    purefa_user:
      description: Create, modify or delete FlashArray local user account
      name: purefa_user
      namespace: ''
      version_added: 1.0.0
    purefa_vg:
      description: Manage volume groups on Pure Storage FlashArrays
      name: purefa_vg
      namespace: ''
      version_added: 1.0.0
    purefa_vlan:
      description: Manage network VLAN interfaces in a Pure Storage FlashArray
      name: purefa_vlan
      namespace: ''
      version_added: 1.0.0
    purefa_vnc:
      description: Enable or Disable VNC port for installed apps
      name: purefa_vnc
      namespace: ''
      version_added: 1.0.0
    purefa_volume:
      description: Manage volumes on Pure Storage FlashArrays
      name: purefa_volume
      namespace: ''
      version_added: 1.0.0
    purefa_volume_tags:
      description: Manage volume tags on Pure Storage FlashArrays
      name: purefa_volume_tags
      namespace: ''
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.15.0
